name: Build and Test Laravel Application

on:
  push:
    branches:
      - staging
      - feature/*

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1  # Adjust to your Laravel app's PHP version
          extensions: mbstring, pdo, curl, dom
          tools: composer

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          composer install
          npm install
          npm run dev

      # Step 4: Set up environment file
      - name: Set up .env file
        run: |
          cp .env.example .env
          php artisan key:generate

      # Step 5: Run Migrations
      - name: Run Database Migrations
        run: |
          php artisan migrate --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: :memory:  # Use in-memory SQLite for tests

      # Step 6: Run Tests
      - name: Run Tests
        run: |
          php artisan test
