name: Build and Test Laravel Application

on:
  push:
    branches:
      - staging
      - feature/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, curl, dom
          tools: composer

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          composer install
          npm install

      # Step 4: Build Production Assets
      - name: Build Production Assets
        run: npm run build

      # Step 5: Set up environment file
      - name: Set up .env file
        run: |
          cp .env.example .env
          php artisan key:generate

      # Step 6: Run Database Migrations
      - name: Run Database Migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan migrate --force

      # Step 7: Run Tests
      - name: Run Tests
        run: php artisan test
